/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React from 'react';
import {StyleSheet, View} from 'react-native';
import SectionedSlider from 'react-native-sectioned-slider';

export default function App() {
  return (
    <View style={styles.container}>
      <SectionedSlider
        style={styles.slider}
        sections={10}
        selectedSection={2}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  slider: {
    backgroundColor: 'green',
    width: 300,
    height: 500,
  },
});
